### ISSUE TITLE
PC 设置弹窗显示不全，无法上下滚动

### ISSUE THREAD

**Issue by Roamin** [yinxin630/fiora#103]
![image](https://user-images.githubusercontent.com/11537595/63070961-cdf1ac80-bf4f-11e9-9ae7-cb3f6eb7460c.png)

碎，你知道了吗
![image](https://user-images.githubusercontent.com/11537595/63070999-f11c5c00-bf4f-11e9-8fd6-8a08755978d9.png)

![image](https://user-images.githubusercontent.com/11537595/63071011-fe394b00-bf4f-11e9-869d-b642872e64c3.png)

**Comment by yinxin630** [comment]
get, 今晚解决

**Comment by yinxin630** [comment]
修了
