### ISSUE TITLE
p2p文件传输

### ISSUE THREAD

**Issue by yinxin630** [yinxin630/fiora#105]
https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API

**Comment by yinxin630** [comment]
demo:
发送者: https://gist.github.com/yinxin630/2db69e020ca9381301466f60cfffbc33
接收者: https://gist.github.com/yinxin630/29da61f1f447551adce868609fc11351
1. 先打开发送者, 获取 `offer`
2. 然后打开接收者, 调用 `setOffer` 参数是上一步的值
3. 获取接收者的 `answer`, 在发送者调用 `setAnswer`
4. 获取接收者的 `candidate`, 在发送者调用 `setCandidate`
5. 连接建立完毕, 开始发送数据

**Comment by yinxin630** [comment]
## 流程梳理
1. 发送者选择文件上传, 本地记录消息id和文件信息, 服务端记录socketId和文件信息
2. 对方发起下载文件请求, 生成一个连接id, 双方存下来
3. 推送连接id给发送方, 开始建立连接, 创建offer, 等待 open 事件
4. 推送offer给接收者, 开始建立连接, 创建answer和candidate, 等待接收数据
5. 推送answer和candidate给发送方, 使连接触发open事件, 开始发送文件
6. 接收方开始接收数据

**Comment by loveqianool** [comment]
因为隐私原因 WebRTC 功能都禁用了，这时候能不能转到服务器中转发送呢？

**Comment by yinxin630** [comment]
目前我想的是, 小文件直接传服务器(过期删除), 大文件走 webRTC 传输

**Comment by loveqianool** [comment]
多大的文件算大文件，还有过期时间，最好是可配置的。

**Comment by zdaiot** [comment]
感觉这个功能还挺实用的，大佬加油～～

**Comment by yinxin630** [comment]
有空继续写吧, 目前发现1对多传输的时候, 信令交换不太好处理
