### ISSUE TITLE
分享群组支持对外分享

### ISSUE THREAD

**Issue by yinxin630** [yinxin630/fiora#110]
- url参数传递群组信息
- 接口需要改造, 允许未登录用户获取任意群组历史消息

**Comment by loveqianool** [comment]
加入群组能设置验证吗？ 群主同意，或者输入正确的密码才能加入群组。现在太开放了，比如我建一个家人群组，其他人只要知道群组名就能随意查看消息。

**Comment by yinxin630** [comment]
> 加入群组能设置验证吗？ 群主同意，或者输入正确的密码才能加入群组。现在太开放了，比如我建一个家人群组，其他人只要知道群组名就能随意查看消息。

有在考虑
