### ISSUE TITLE
前端运行白屏, 报错信息包含 "class-name"

### ISSUE THREAD

**Issue by jojostops** [yinxin630/fiora#112]
安装后程序运行无报错，首页空白源码中有部分CSS和JS数据无body，疑似代码更新后出现bug。

该错误已和moerats站长确认，非偶然因素。

**Comment by yinxin630** [comment]
我试着跑了一遍没问题啊

**Comment by jojostops** [comment]
不知问题何处，我俩现在都搭不出来，大佬要不加个好友，我在你的群里at你了，我把服务器给你看看

**Comment by yinxin630** [comment]
定位是 `prisejs` 这个模块有问题, 我再详细看看   
用 yarn 安装依赖就没问题, 因为锁了模块版本, 本问题是用 npm install 安装的依赖, 遇到类似问题的可以试试 yarn
