### ISSUE TITLE
关于图片上传失败

### ISSUE THREAD

**Issue by yzg9540** [yinxin630/fiora#129]
用docker安装的，这也是刚学的
七牛云貌似需要域名备案？
自己瞎完，服务器上传图片就行

http://172.18.0.3:9200/ImageMessage_5d6c7499c3cf20001ad9eb4c_1567399926710.png?width=180&height=180&imageView2/3/w/216/h/216
上传图片报错这个
估计是容器的ip吧

请问大佬具体怎么改啊

https://github.com/yinxin630/fiora/issues/82
一句代码也不会，纯粹好玩，烦请大佬详细指教下

host: options.host || env.Host || ip.address(),
这个东西研究了一上午也没鼓捣出来

改完需要怎样重启，才能生效？

**Comment by yinxin630** [comment]
参考: #113

**Comment by yinxin630** [comment]
host: 后面内容删掉, 直接填你实际ip或者域名, 譬如 '1.2.3.4` 或者 'http://fiora.xxx.com'
