### ISSUE TITLE
聊天室无法显示头像

### ISSUE THREAD

**Issue by assidence** [yinxin630/fiora#131]
改了聊天室和自己的头像后，正常了一段时间，然后开始无法显示头像。
![批注 2019-09-09 015025](https://user-images.githubusercontent.com/15117775/64492262-c4383c00-d2a4-11e9-812e-2723e00576ae.png)

**Comment by assidence** [comment]
我发现web客户端跑到9200端口读图片了，但是我使用了nginx反代，请问怎么让客户端到443端口读图片

**Comment by yinxin630** [comment]
执行 `npm start` 用 production 模式运行, 这样子图片路径是一个自适应 host 的路径

**Comment by yinxin630** [comment]
关注 #132
