### ISSUE TITLE
Docker镜像按教程无法在开发板上运行

### ISSUE THREAD

**Issue by walkonbothsides** [yinxin630/fiora#135]
香橙派One，**Debian Buster**环境
可docker logs只有一行
`standard_init_linux.go:211: exec user process caused "exec format error"`
是我的打开方式不对吗？

**Comment by yinxin630** [comment]
开发版我没搞过啊.. 不知道和普通机器有啥区别, 没法帮到你

**Comment by walkonbothsides** [comment]
> 开发版我没搞过啊.. 不知道和普通机器有啥区别, 没法帮到你

- 等同于一部用ARM的CPU的装了Debian的电脑（至少现在是）
- 这个错误代码我能了解到的就是因为docker没有arm的镜像所以不兼容x86的镜像
- 所以所以 @yinxin630 有编译arm版本的打算吗（期待脸.jpg）
- 现在一直只能用Rocket.Chat的snap包，有点偏爱fiora啊

**Comment by yinxin630** [comment]
是需要我这边基于一个 arm 镜像去构建 fiora 镜像吗

**Comment by walkonbothsides** [comment]
> 是需要我这边基于一个 arm 镜像去构建 fiora 镜像吗

诶也许是个方法
但是我掏出我的树莓派`yarn`或者`npm i`都会死在`pure-render-decorator`这个依赖，望知悉
谢啦

**Comment by yinxin630** [comment]
主要我没有你这个环境, 能在一台 MAC 上模拟你的开发板环境吗?

**Comment by walkonbothsides** [comment]
> 主要我没有你这个环境, 能在一台 MAC 上模拟你的开发板环境吗?
理论上只要能用虚拟机跑armhf架构版本得Debian Buster就行了
或者说需要我做些什么吗

**Comment by yinxin630** [comment]
我先自己研究下看看..

**Comment by walkonbothsides** [comment]
在网上查了一下发现似乎要动用qemu搭建arm环境，有点麻烦啊XP
所以 @yinxin630 需要我提供开发板的环境吗，我可以开远程ssh什么的

**Comment by yinxin630** [comment]
能有 ssh 就最好了

**Comment by walkonbothsides** [comment]
> 能有 ssh 就最好了

那等我州一下午考完试联系
达成共识.jpg

**Comment by walkonbothsides** [comment]
> 能有 ssh 就最好了

您的Gmail有一封邮件，请注意查收

**Comment by KiritakeKumi** [comment]
想问下...这个问题是否有解决方案了??
我这也是arm64的设备..报错也是和上面一样.
root@NicoBOX-X1:~# docker run --name fiora -p 9200:9200 --network fiora-network -e Database=mongodb://fioradb:27017/fiora suisuijiang/fiora
standard_init_linux.go:211: exec user process caused "exec format error"

设备情况:
Linux NicoBOX-X1 4.4.174-rockchip64 #6 SMP Sun Feb 10 10:43:16 CET 2019 aarch64

**Comment by yinxin630** [comment]
我在楼主的机器上直接 clone 源码跑是可以的

**Comment by walkonbothsides** [comment]
0w0我成功在RPi 4(arm64环境)跑docker镜像了2333 @yinxin630 
我微改了下自己fork的Dockerfile，构建运行成功了，你可以从我fork的那份单独clone一份然后自己按照自己编译docker镜像的教程构建一下 @pukanxi 
当然最好是把我的Dockerfile拿替换官方源码的那份再自己编译（因为可以保持最新）
当然主要是我不知道fork改代码后如何保持最新

**Comment by yinxin630** [comment]
在 fork 的仓库定期 merge 下主仓库的 master 分支, 就保持最新啦

**Comment by KiritakeKumi** [comment]
感谢回复.
另外.请问是否有想法编译已经做好的docker镜像上传至公共库呢?
@walkonbothsides 
我的板子上的CPU..可能编译起来十分困难..

**Comment by walkonbothsides** [comment]
> 感谢回复.
> 另外.请问是否有想法编译已经做好的docker镜像上传至公共库呢?
> @walkonbothsides
> 我的板子上的CPU..可能编译起来十分困难..

已上传至Hub，只要将原教程中`直接拉取dockerhub镜像运行`那部分中的`suisuijiang/fiora`替换成`megaflops/fiora-arm64`即可
祝你好运
所以我的32位环境怎么办QAQ

**Comment by KiritakeKumi** [comment]
> > 感谢回复.
> > 另外.请问是否有想法编译已经做好的docker镜像上传至公共库呢?
> > @walkonbothsides
> > 我的板子上的CPU..可能编译起来十分困难..
> 
> 已上传至Hub，只要将原教程中`直接拉取dockerhub镜像运行`那部分中的`suisuijiang/fiora`替换成`megaflops/fiora-arm64`即可
> 祝你好运
> 所以我的32位环境怎么办QAQ

感谢...我已搭建完成并正常运行

armv7环境...我手上也没有设备可供测试唉..

**Comment by icecliffs** [comment]
> megaflops/fiora-arm64

谢谢您
