### ISSUE TITLE
表情包搜索功能挂了

### ISSUE THREAD

**Issue by yinxin630** [yinxin630/fiora#145]
搜不到了

**Comment by yzg9540** [comment]
http://weshineapp.com/


个人建议：
图片流水化显示，去掉搜索，借鉴  闲聊么

**Comment by yinxin630** [comment]
http://www.dbbqb.com/s?w=%E6%A3%92%E6%A3%92%E5%93%92

**Comment by b7bq** [comment]
https://www.b7.cn/so/bq/index.php?page=10&keyboard=%E6%A3%92%E6%A3%92%E5%93%92    试一下这个

**Comment by yinxin630** [comment]
> https://www.b7.cn/so/bq/index.php?page=10&keyboard=%E6%A3%92%E6%A3%92%E5%93%92 试一下这个

有开放API吗, 文档在哪

**Comment by yinxin630** [comment]
已修复
