### ISSUE TITLE
本地配置完 RUN 成功 提示请执行 "npm run client" 运行客户端 或者执行 "npm run build" + "npm run move-dist" 构建静态客户端

### ISSUE THREAD

**Issue by deway** [yinxin630/fiora#150]
本地配置完 RUN 成功 提示请执行 "npm run client" 运行客户端 或者执行 "npm run build" 
服务端
[nodemon] 1.19.4
[nodemon] reading config .\.nodemonrc
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 7916 to restart
[nodemon] ignoring: client/**/* build/**/* test/**/* public/**/* dist/**/* test.js
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `./node_modules/.bin/ts-node server/main.ts`
[nodemon] spawning
[nodemon] child pid: 11812
[nodemon] watching 253 files
(node:13976) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
 >>> server listen on http://localhost:9200

客户端
ERROR in D:\jswww\fiora\client\modules\Chat\Expression.tsx
./client/modules/Chat/Expression.tsx
[tsl] ERROR in D:\jswww\fiora\client\modules\Chat\Expression.tsx(98,25)
      TS2322: Type '{ className: any; src: any; alt: string; key: any; referrerPolicy: string; onClick: (e: any) => void; }' is not assignable to type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'.
  Property 'referrerPolicy' does not exist on type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'.

ERROR in D:\jswww\fiora\client\modules\Chat\Message\ImageMessage.tsx
./client/modules/Chat/Message/ImageMessage.tsx
[tsl] ERROR in D:\jswww\fiora\client\modules\Chat\Message\ImageMessage.tsx(82,25)
      TS2322: Type '{ className: any; src: string; alt: string; width: number; height: number; onClick: () => void; referrerPolicy: string; }' is not assignable to type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'.
  Property 'referrerPolicy' does not exist on type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'.
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.36 MiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./client/templates/index.html] 1.75 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
> Listening at http://localhost:8080

**Comment by yinxin630** [comment]
你打开的地址是什么

**Comment by deway** [comment]
就是本地地址:9200   和 :8080   都是一样的提示
请执行 "npm run client" 运行客户端 
或者执行 "npm run build" + "npm run move-dist" 构建静态客户端

环境nodejs 12.13   mongo  4.2.1  都是最新的

**Comment by yinxin630** [comment]
是服务器吗, 我登录上去看看

**Comment by yinxin630** [comment]
我又本地试了一下, 没发现问题

**Comment by deway** [comment]
谢谢解答，自己最后忘了配置NGINX 反向

**Comment by deway** [comment]
这个问题解决

**Comment by ibcLee** [comment]
> 谢谢解答，自己最后忘了配置NGINX 反向

同样的问题，nginx还需要如何配置？

**Comment by deway** [comment]
install  说明 最后面   nginx 配置     9200 这个

**Comment by ztacg18** [comment]
我是windows端部署玩了下，也报这个错，我把报错组件中img的referrerPolicy属性删掉了，就能运行起来了😂（不知道是什么问题，是属性不兼容？我是后端开发这块属性的东西不太了解

**Comment by yinxin630** [comment]
@ztacg18 是 ts 版本不一致问题, 我这里没报错, 你们装了新版会报错, 已修复
#150 相关

**Comment by DENNIE-HONG** [comment]
报错TSError: ⨯ Unable to compile TypeScript:
![image](https://user-images.githubusercontent.com/23476088/83246124-3f93a200-a1d4-11ea-8baa-c8477fefb77d.png)

**Comment by yinxin630** [comment]
> 报错TSError: ⨯ Unable to compile TypeScript:
> ![image](https://user-images.githubusercontent.com/23476088/83246124-3f93a200-a1d4-11ea-8baa-c8477fefb77d.png)

是用 yarn 安装的依赖吗

**Comment by DENNIE-HONG** [comment]
> > 报错TSError: ⨯ Unable to compile TypeScript:
> > ![image](https://user-images.githubusercontent.com/23476088/83246124-3f93a200-a1d4-11ea-8baa-c8477fefb77d.png)
> 
> 是用 yarn 安装的依赖吗



> > 报错TSError: ⨯ Unable to compile TypeScript:
> > ![image](https://user-images.githubusercontent.com/23476088/83246124-3f93a200-a1d4-11ea-8baa-c8477fefb77d.png)
> 
> 是用 yarn 安装的依赖吗

不是，用的npm i , 用npm run build, 也做校验，编译也不过. "typescript": "^3.7.2",

**Comment by yinxin630** [comment]
@DENNIE-HONG 
typescript 版本要保持和 lock 的版本号(`typescript@3.8.2`)完全一致, `npm list typescript` 可以查看本地安装的实际版本号

还有, 你现在执行的是 `npm run server` 吗, `npm start` 应该已经去掉 typescript 校验了, 生产模式用 `npm start`

`npm run build` 会分为两个过程, `创建构建任务` 和 `webpack 编译`, 过程二会校验, 我感觉也可以去掉, 后面有时间看看
