### ISSUE TITLE
新问题：修改了client 代码 build 了，但是浏览器访问还是没改动

### ISSUE THREAD

**Issue by deway** [yinxin630/fiora#151]
试了好多便，修改了client 代码 ,构建静态客户端 `npm run build`
将客户端构建产物移到服务端静态资源目录 `npm run move-dist`
浏览器也每次都清缓存，但是问题还是出现的界面 是 没有改动过的，原始界面？
这个是？啥子情况

**Comment by yinxin630** [comment]
确认每一步都是成功的, 没报错吗

**Comment by dalaolala** [comment]
小可爱碎碎
这个问题我也遇到了 静态文件不更新 打死都不更新 ！！！
可能是nginx反代的问题 

目前解决方案：

nginx的配置文件
```
proxy_pass         http://localhost:9200;

改成

proxy_pass         http://外网的ip地址:9200;

```

刷新浏览器，再改回去就可以了

**Comment by dalaolala** [comment]
> 确认每一步都是成功的, 没报错吗

小可爱碎碎
这个问题我也遇到了 静态文件不更新 打死都不更新 ！！！
可能是nginx反代的问题

**Comment by yinxin630** [comment]
@dalaolala 你们的静态资源是不是没放 CDN, 直接从服务器响应的? 是不是 nginx 缓存规则配置的不对呢?

**Comment by dalaolala** [comment]
> @dalaolala 你们的静态资源是不是没放 CDN, 直接从服务器响应的? 是不是 nginx 缓存规则配置的不对呢?

嗯嗯嗯  我又研究了下  确实是nginx的问题 把nginx的缓存全部清理掉就好啦

**Comment by yinxin630** [comment]
好的, 后面同学可以参考, 这个先关了
