### ISSUE TITLE
安卓点击网页链接后退出且再次登录时要重新输入账号密码

### ISSUE THREAD

**Issue by xxrrxnb** [yinxin630/fiora#154]
希望实现安卓端自动登录，记住账号的功能

**Comment by yinxin630** [comment]
自动登录有的, 你是不是开的无痕(隐私)模式?   
记住账号不会做的, 现在浏览器都有记住账号功能

**Comment by xxrrxnb** [comment]
好的哇


 
---原始邮件---
发件人: "碎碎酱"<notifications@github.com&gt;
发送时间: 2019年12月20日 09:28:49
收件人: "yinxin630/fiora"<fiora@noreply.github.com&gt;;
抄送: "UniqueMe"<1428717646@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [yinxin630/fiora] 安卓点击网页链接后退出且再次登录时要重新输入账号密码 (#154)



自动登录有的, 你是不是开的无痕(隐私)模式?
 记住账号不会做的, 现在浏览器都有记住账号功能
