### ISSUE TITLE
怎么设置关闭注册啊

### ISSUE THREAD

**Issue by ldxw** [yinxin630/fiora#164]
在哪里设置关闭注册啊

**Comment by yinxin630** [comment]
暂时不支持该需求, 想实现的话, 可以自行修改代码
1. 客户端中注释掉"注册"面板<https://github.com/yinxin630/fiora/blob/master/client/modules/LoginAndRegister/LoginAndRegister.tsx#L33-L35>
2. 服务端中注释掉"register"接口 <https://github.com/yinxin630/fiora/blob/master/server/routes/user.ts#L78-L128>
3. 抄"register"接口的逻辑, 自己实现服务端创建新用户

**Comment by yinxin630** [comment]
#67 相关

**Comment by ldxw** [comment]
> #67 相关



> #67 相关

那服务端注册命令多少啊？

**Comment by ldxw** [comment]
> 暂时不支持该需求, 想实现的话, 可以自行修改代码
> 
> 1. 客户端中注释掉"注册"面板https://github.com/yinxin630/fiora/blob/master/client/modules/LoginAndRegister/LoginAndRegister.tsx#L33-L35
> 2. 服务端中注释掉"register"接口 https://github.com/yinxin630/fiora/blob/master/server/routes/user.ts#L78-L128
> 3. 抄"register"接口的逻辑, 自己实现服务端创建新用户

用 /*  */ 注释 拉取后怎么直接加了/*  */ 这个注释不掉，只能删掉啊

**Comment by yinxin630** [comment]
要不等我来实现吧

**Comment by ldxw** [comment]
> 要不等我来实现吧

先说说，我先玩着，等功能出来在换。。哈哈

**Comment by yinxin630** [comment]
已经实现了, 拉取 master 即可   
等会补上使用文档

**Comment by ldxw** [comment]
> 已经实现了, 拉取 master 即可
> 等会补上使用文档

直接拉取覆盖是吧

**Comment by yinxin630** [comment]
是的, 配置请参考 <https://github.com/yinxin630/fiora/blob/master/doc/INSTALL.ZH.md#%E7%A6%81%E6%AD%A2%E6%B3%A8%E5%86%8C-%E6%89%8B%E5%8A%A8%E5%88%86%E9%85%8D%E8%B4%A6%E5%8F%B7>
