### ISSUE TITLE
怎么获取ROOT权限，这个字段怎么改？

### ISSUE THREAD

**Issue by 8373907** [yinxin630/fiora#169]
// administrator user id
    administrator: options.administrator || env.Administrator || '',

假如ID是5d329dd354b9，修改为这样吗？
// administrator user id

administrator: options.5d329dd354b9 || env.Administrator || '',

**Comment by yinxin630** [comment]
将 id 填到末尾的空字符串内   
`administrator: options.5d329dd354b9 || env.Administrator || '5d329dd354b9'`
