### ISSUE TITLE
1H1G 的轻量服务器编译时 cpu负载20+ 运行npm start时 负载15+

### ISSUE THREAD

**Issue by imjonat** [yinxin630/fiora#171]
环境：

- `centos7.3  nvm的node v12.16.0 ` 与 `centos7.3  nvm的node v10.19.0 ` 都存在该问题

情况说明：

- 编译(`npm run build`)时候`top`中负载飙升20+，十秒后服务器未响应

- 可能5%情况下卡10分钟会编译成功 其余时候机器响应很慢，top下数据刷新由原来1次/s 变成n秒刷新一次，大部分时间都没有编译成功，后来就只好自己机器编译提取public

- 执行`npm start`时也特别卡

> 因为图个方便，想要一个服务器搭建完成，就用caddy反代9200端口，所以不打算前后端分离放在oss上，才遇到这个问题

提出疑问：

- 本人完美黑苹果下一切正常（可能因为i5-9400f 性能相对1H更强大所以不会卡，仅仅猜测）

- 回想到`commit e92ff21`也就是我pr的那时候，启动的是`main.js`文件。**遂回滚版本，发现编译和运行都很快**，非常快的那种，但是个人喜欢用更新的版本

需求帮助：

- 现在就是很无奈……一编译就卡 只能本地编译好再tar上去。但是问题来了，改配置还是需要重启服务器，`npm start`后 80%的情况下卡死未响应……

BTW：

- 在用到[file.pizza](url)的时候发现了[file.io](url)，应该也是个不错网站 `(#^.^#)`

图片：
- 截图了！！但是忘了丢哪了……有空再开一个轻量服务器截个图

**Comment by yinxin630** [comment]
编译卡的问题应该没法解决, 因为编译过程是 CPU 计算加文件读写, 性能消耗大, 或者可以看看 webpack 能不能设置编译时 CPU 使用率上限

npm start 慢的问题是因为代码从 JavaScript 切到了 TypeScript, 之前是用 node 跑的, 现在使用 ts-node 跑, ts-node 内部都做了啥我不太清楚, 可以探索下把 ts 代码手动编译为 js, 再执行

**Comment by imjonat** [comment]
> 编译卡的问题应该没法解决, 因为编译过程是 CPU 计算加文件读写, 性能消耗大, 或者可以看看 webpack 能不能设置编译时 CPU 使用率上限
> 
> npm start 慢的问题是因为代码从 JavaScript 切到了 TypeScript, 之前是用 node 跑的, 现在使用 ts-node 跑, ts-node 内部都做了啥我不太清楚, 可以探索下把 ts 代码手动编译为 js, 再执行

好嘛，我不太熟webpack……求各路大师指点迷津

确实想探索下ts编译js。公司前项目是开发用ts，上线仅运行编译后的js代码，**等我的pr**

**Comment by imjonat** [comment]
> 编译卡的问题应该没法解决, 因为编译过程是 CPU 计算加文件读写, 性能消耗大, 或者可以看看 webpack 能不能设置编译时 CPU 使用率上限
> 
> npm start 慢的问题是因为代码从 JavaScript 切到了 TypeScript, 之前是用 node 跑的, 现在使用 ts-node 跑, ts-node 内部都做了啥我不太清楚, 可以探索下把 ts 代码手动编译为 js, 再执行

![image](https://user-images.githubusercontent.com/42567368/74909228-c5909780-53f2-11ea-8901-8d3e6e4600c5.png)

- 目前编译server代码至js成功 编译也很快 服务端可正常运行 不过遇到一个`npm run client`的报错 看了几圈 不太懂……
![image](https://user-images.githubusercontent.com/42567368/74910085-a430ab00-53f4-11ea-882a-dd8e7765f985.png)

**Comment by yinxin630** [comment]
./build/dev-client.ts 文件还在吗

**Comment by imjonat** [comment]
> ./build/dev-client.ts 文件还在吗

- 在的 推上了这个仓库
大概思路是`npm run build-server`编译的时候出一份`dist/src/*`版本代码 运行的时候使用pm2 start xxx.js --env xxxx 会比较方便管理

https://github.com/imjonat/fiora

**Comment by yinxin630** [comment]
把你的改动提一下 PR 吧, 方便看 😃

**Comment by yinxin630** [comment]
关联 #173
