### ISSUE TITLE
fiora打不开

### ISSUE THREAD

**Issue by threescs** [yinxin630/fiora#175]
碎, fiora打不开了

**Comment by yinxin630** [comment]
被 DDos 攻击了

**Comment by threescs** [comment]
防火墙限制下端口？




| |
尚成帅
|
|
邮箱：threescs@163.com
|

签名由 网易邮箱大师 定制

在2020年03月03日 23:01，碎碎酱 写道：

Closed #175.

**Comment by yinxin630** [comment]
阿里云有 DDos 防护, 但是因为攻击流量超过了免费额度, 阿里云自动给我进入黑洞模式了
