### ISSUE TITLE
建议给图片消息增加一个缩略图的字段，由后端提供缩略图地址

### ISSUE THREAD

**Issue by iyjian** [yinxin630/fiora#187]
现在消息中的图片在点开的时候会被前端强制加上一个七牛的图片处理指令，这个对后期接入其他cdn就不友好，可以增加一个缩略图的字段，前端直接使用这个字段，这样我可以把我自己的阿里oss的对接代码放上来。

**Comment by yinxin630** [comment]
写一个 CDN 适配方法就行, 所有直接添加七牛指定的地方改为调用工具方法. 我手术也没有别的 CDN 资源, 懒得搞

**Comment by yinxin630** [comment]
单独搞个缩略图字段就没必要了, 任何图都可以通过图片参数由 CDN 来生成

**Comment by iyjian** [comment]
现在对图片进行裁剪的指令是你在前端写死的，你意思如果我加其他cdn的适配了你前端也对应增加吗？

**Comment by iyjian** [comment]
我现在自己弄的是阿里的oss，然后前端传过来的裁剪指令还是七牛的   这样子我的聊天室就一直点不开图片。

**Comment by yinxin630** [comment]
将 CDN 处理插件化, 定义参数规范, 有其它 CDN 需求就可以按照规范来自行实现

**Comment by yinxin630** [comment]
关联 #167
