### ISSUE TITLE
关于消息内容加密

### ISSUE THREAD

**Issue by chopinsong** [yinxin630/fiora#194]
hello，项目不错，挺喜欢的。不过发现无论是长连接还是短连接，消息内容都没有加密。
我对nodejs不熟悉，无从入手。大佬是否可以考虑加密？

**Comment by yinxin630** [comment]
目前是依赖于 https 对中间传输过程加密. 不知道你所希望的加密是什么形式的?

**Comment by chopinsong** [comment]
我指的是 如果抓包的话。消息内容等直接显示的明文

**Comment by yinxin630** [comment]
https 已经可以防止抓包了
