### ISSUE TITLE
真的不支持Windows Server吗

### ISSUE THREAD

**Issue by yuameshi** [yinxin630/fiora#197]
服务器提供商：阿里云
实例规格： ecs.s6-c1m2.small
实例规格族： ecs.s6
实例类型： I/O优化
所在可用区： 华北 3 可用区 C
地域： 华北3（张家口）
当前使用带宽： 1Mbps
操作系统：Windows Server  2012  R2 数据中心版 64位中文版
Server：Microsoft-Internet Information Service/8.5
CPU：Intel Xeon 8269CY@2.50GHz （1颗核心）
内存：2GiB
Node.js版本：12.18.1 LTS
MongoDB版本：mongodb-win32-x86_64-2008plus-ssl-v4.0-latest-signed
(下载地址：http://downloads.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-v4.0-latest-signed.msi)
安装方式：npm install
问题：npm run server/npm run cilent /npm start均无法正常启动
在执行过npm run build、npm run lint后还是不行
是WebPack要另外安装还是咋的
@yinxin630 Log我会附在下面，要是真的搞不了那就我自己搞一个简单的PHP版吧

[npm run server的CMD回显](https://github.com/yinxin630/fiora/files/4823566/npm.run.server.txt)
[npm run client的CMD回显](https://github.com/yinxin630/fiora/files/4823578/npm.run.client.txt)
[2020-06-24T06_19_11_715Z-debug.log](https://github.com/yinxin630/fiora/files/4823584/2020-06-24T06_19_11_715Z-debug.log)
[2020-06-24T06_19_42_011Z-debug.log](https://github.com/yinxin630/fiora/files/4823586/2020-06-24T06_19_42_011Z-debug.log)

**Comment by yinxin630** [comment]
抱歉现在才回复. 看 `npm run server` 和 `npm run client` 的输出, 都是 typescript 校验没过, 你是用开发模式启动的所以会校验, 你可以直接用 `npm run build`(client) 和 `npm start` (server) 来启动

在 windows 上的兼容性确实没测试过, 建议用 docker 来跑

**Comment by yuameshi** [comment]
不过似乎npm run build也不太行，npm start的运行结果和npm run cilent一样【捂脸】
[npm run build的CMD回显](https://github.com/yinxin630/fiora/files/4855269/npm.run.build.txt)

**Comment by yinxin630** [comment]
最近修改了构建配置, 可能有助于在 windows 系统运行, 先关闭该 issue, 如果有问题的话请 reopen
