### ISSUE TITLE
websocket端口

### ISSUE THREAD

**Issue by ravizhan** [yinxin630/fiora#198]
请问能否自定义ws端口，实现ws端口与http端口**不同**
例如：访问 **xxx.com**,
请求 ws://xxx.com:**8080**/socket.io/?EIO=3&transport=websocket&sid=XXXXXXX
而不是 ws://**xxx.com**/socket.io/?EIO=3&transport=websocket&sid=XXXXXXX

**Comment by yinxin630** [comment]
可以的, 但是要考虑到端口号不同引起的跨域问题
修改 <https://github.com/yinxin630/fiora/blob/master/config/client.ts#L4> 末尾的空字符串即可
