### ISSUE TITLE
You need an FAQ, really

### ISSUE THREAD

**Issue by blackmiaool** [yinxin630/fiora#21]
Or use an AI to detect newbies' questions and answer them automatically.

**Comment by huangzhuangjia** [comment]
我启动的时候socket.io报net::ERR_CONNECTION_REFUSED错误，不能连接服务器，请问怎么解决呢大神

**Comment by yinxin630** [comment]
@JungaH520  有没有在config.js中正确的配置呢? 或者, 是不是意外启动了两份, 造成端口重复?

**Comment by l20** [comment]
请问支持点到点私聊功能吗？
