### ISSUE TITLE
双击选中复制消息会复制到楼下的头衔

### ISSUE THREAD

**Issue by AdminHcat** [yinxin630/fiora#216]
![image](https://user-images.githubusercontent.com/50044729/89511845-ffb8ee80-d804-11ea-8ed3-17c4d67fe000.png)

**Comment by yinxin630** [comment]
实测的时候很奇怪, ctrl+c 或者右键选择复制的结果都是正确的, 但右键菜单里的相关功能展示的文本却不对

把 tag 设置为可选中文本就没问题了
