### ISSUE TITLE
在线人数始终为0

### ISSUE THREAD

**Issue by wegood9** [yinxin630/fiora#217]
无法获取群组的在线成员以及好友的在线状态，但是管理员可以读取用户ip

环境：docker以及npm开发模式运行均出现此问题

**Comment by yinxin630** [comment]
方便的话让我登上去 debug 看看?

**Comment by wegood9** [comment]
请问需要提供些什么，ssh还是聊天室地址？

**Comment by yinxin630** [comment]
需要 SSH, 我要修改代码调试看看. 方便的话聊天室私聊我
