### ISSUE TITLE
如何将新用户修改为老用户

### ISSUE THREAD

**Issue by HtnrxUNc** [yinxin630/fiora#221]
因为萌新期的调用限制，所以不知道如何将用户更换为老用户，是否为
`type Options = {
    maxCallPerMinutes?: number;
    newUserMaxCallPerMinutes?: number;
    clearDataInterval?: number;
}`
中更改，将number更改为用户id
多个用户id使用,分割

**Comment by yinxin630** [comment]
新用户的标识目前是存在内存里的, 每次用户登录时都会校验一下注册时间是否满 24 小时, 不满就存个标识

你需要修改这处判断新用户的逻辑
https://github.com/yinxin630/fiora/blob/master/server/routes/user.ts#L49-L62

或者注释掉这里对新用户的拦截
https://github.com/yinxin630/fiora/blob/master/server/middlewares/frequency.ts#L45-L53
