### ISSUE TITLE
How to develop fiora on windows

### ISSUE THREAD

**Issue by blackmiaool** [yinxin630/fiora#24]
1 Install virtualbox
2 Install ubuntu into virtualbox
3 Set configuration of network as "bridged adapter"
4 Install openssh-server and git into ubuntu 
5 Install WinSSHFS and Dokan into windows
6 Use WinSSHFS to connec ubuntu
7 Confirm that the webpack server command has the parameter "--host 0.0.0.0"
8 Edit your config file
9 Run npm install and npm start
10 Open the ip of your ubuntu on windows (e.g. http://192.168.1.110:8080/)

**Comment by imengmengda** [comment]
spicy chicken！
