### ISSUE TITLE
用户现在可以和自己聊天

### ISSUE THREAD

**Issue by shisaq** [yinxin630/fiora#27]
好棒的聊天室！！！

我发现我可以和自己聊天，发了这一条后，又收到这一条，这似乎不太合适。

建议：

1. 禁止和自己聊天；

2. 可以聊，但只接收1条信息（类似QQ的文件管理器）。

祝好。

**Comment by yinxin630** [comment]
我取消给自己发送消息的入口吧, 原来就考虑过, 一直没动手

**Comment by yeyuguo** [comment]
我觉得蛮好的呀  在QQ上 我都经常使用和自己聊天的功能啊，有些东西，不一定要收藏，发给自己的聊天框 超级好用呀

**Comment by yinxin630** [comment]
@yeyuguo 私聊并不会加载历史记录, 和自己私聊会显示两条消息(发出去的一条, 收到的一条). 等后续功能优化后我会再添加和自己聊天的功能.
