### ISSUE TITLE
此问题纯是请教！

### ISSUE THREAD

**Issue by FengHaiSheng** [yinxin630/fiora#28]
此项目的构建用到了工具吗？
这么多配置项，大神是如何提前知道的，还是经验所成？
这个项目简直就是我再走的学习路线，太棒了！
大神收徒吗？

**Comment by yinxin630** [comment]
这个项目的构建工具是 webpack, 是基于 [vue-cli](https://github.com/vuejs/vue-cli) 这个 vue 项目脚手架做的 react 项目改装.

**Comment by FengHaiSheng** [comment]
我跟那个看了你的博客，你很努力，虽然我是2016年5月开始走的全栈这个路线。差不多一年，熟练了CSS,HTML,学会了JS和node.js的基本使用，webpack的配置。但是感觉个你的努力程度远超过我，而且你也在北京，很高兴今天能发现这个项目。也希望以后能多与你交流。这个github账号是工作用的。

**Comment by yinxin630** [comment]
加油, 聊天室我大部分时间都在, 随时交流
