### ISSUE TITLE
添加管理id之后无法启动

### ISSUE THREAD

**Issue by HtnrxUNc** [yinxin630/fiora#287]
当我尝试按照步骤安装fiora时候，它成功运行了，没有任何的错误

当我添加管理id时，它显示了错误
管理员配置项修改为如下

     // administrator user id administrator: env.Administrator ? env.Administrator.spl it(',') : [5fdec0af320b20f6b98d5348],

当我运行  yarn start  时显示的报错为

    return new TSError(diagnosticText, diagnosticCodes)
           ^
    TSError: ⨯ Unable to compile TypeScript:
    config/server.ts:40:73 - error TS1351: Anidentifier or keyword cannot immediately follow a numericliteral.

     40     administrator: env.Administrator ? env.Administrator.split(',') : [5fdec0af320b20f6b98d5348],

预期行为:添加成功id之后成功运行

个人猜测:
是否因为id填写的格式错误？

版本:最新版

排班可能有问题，来自我的连接器bug

**Comment by HtnrxUNc** [comment]
我已经成功解决该问题
当我将用户id使用 "" 赋值时
成功运行
也就是将管理员id那行改为
    // administrator user id
    administrator: env.Administrator ? 
    env.Administrator.spl it(',') : 
   "5fdec0af320b20f6b98d5348",

**Comment by yinxin630** [comment]
`administrator` 字段需要为 String 类型数组, 应该填入 `['5fdec0af320b20f6b98d5348']`
