### ISSUE TITLE
使用CDN后，无法注册，提示系统错误

### ISSUE THREAD

**Issue by muzi9527** [yinxin630/fiora#307]
把判断24小时只能注册一次的相关代码注释掉就好了，这部分的判断是否可以优化一下？

**Comment by yinxin630** [comment]
现在是 24 小时内允许注册三次, 完全能够满足正常用户需求了. 这么做是为了防止恶意攻击
管理员还可以执行命令 `yarn script register [用户名] [密码]` 来注册用户
