### ISSUE TITLE
Error: Cannot find module '../bin/doctor'

### ISSUE THREAD

**Issue by delsinz** [yinxin630/fiora#308]
Threw this error when I tried to run the project with docker.

**Comment by delsinz** [comment]
It seems bin folder is not copied in dockerfile

**Comment by yinxin630** [comment]
Are you running this image? <https://hub.docker.com/r/suisuijiang/fiora>
Or build it yourself?

**Comment by delsinz** [comment]
> Are you running this image? https://hub.docker.com/r/suisuijiang/fiora
> Or build it yourself?

Tried both pulling the image from dockerhub and building the image myself.

**Comment by delsinz** [comment]
![Screen Shot 2021-02-09 at 11 51 28](https://user-images.githubusercontent.com/17754103/107300241-3847c680-6acd-11eb-987b-ccd9b3c9392c.png)
Clearly the bin folder is not copied. It worked flawlessly after I changed the dockerfile to copying everything in the root directory.
