### ISSUE TITLE
Incorrect port mapping in docker-compose file

### ISSUE THREAD

**Issue by delsinz** [yinxin630/fiora#309]
![Screen Shot 2021-02-08 at 13 54 05](https://user-images.githubusercontent.com/17754103/107170881-93b67d80-6a15-11eb-9931-aa81085d478d.png)

App is running on port 9999 in the container according to docker-compose file, but port 9200 is mapped to local machine.

**Comment by yinxin630** [comment]
Thanks for reminding, I will fix this issue later
