### ISSUE TITLE
执行npm run dev的时候遇到的报错

### ISSUE THREAD

**Issue by DTbelieveIT** [yinxin630/fiora#31]
node：7.90  
npm ： 4.10
我按照README.md的安装步骤， 执行npm run dev时遇到了下面的报错
 ERROR  Failed to compile with 1 errors
* react/lib/getNextDebugID in ./~/react-dom/lib/instantiateReactComponent.js
To install it, you can run: npm install --save react/lib/getNextDebugID

下面有出现“ Listening at http://localhost:8080”，但是打开localhost:8080出现的结果是Get / 404
另一个命令npm run server可以打开，请问又遇到这种情况吗

**Comment by yinxin630** [comment]
没有遇到过, 看起来是react安装不正确, 试试单独安装react, 或者换版本试试(15.3 or 15.4)

**Comment by DTbelieveIT** [comment]
试过了，还是一样，请问你的node版本是多少？对啦，你是不是在mac平台下开发的，在window下安装"bcrypt": "^1.0.2"相当费劲，我记得之前在开发一个项目想用，可惜安装不成功，后来用node-bcrypt了

**Comment by yinxin630** [comment]
node 版本我用的7.6以上, mac平台.

**Comment by Holl9** [comment]
同样是这个问题，请问怎么解决的？ 是版本不对吗

**Comment by newshell** [comment]
react 版本跟react-dom版本不兼容 改一下react版本就好了

**Comment by yinxin630** [comment]
感谢 @newshell , 有问题的同学可以试试看, 最近在研究docker, 以后会发布docker版本, 避免繁杂的环境和应用配置
