### ISSUE TITLE
【bug】由于登录时查询语句错误，导致处于被加方的好友，重新登录时无法获取好友的聊天信息

### ISSUE THREAD

**Issue by Insistem** [yinxin630/fiora#310]
# 问题描述： 
    `用户A`主动加`用户B`为好友，两人都在登录状态，两边的消息显示都正常。如果`用户B`下线了，然后重新登录后，聊天界面就无法显示与`用户A`的聊天列表了

# 问题分析：
```js
const friends = await Friend.find({ from: user._id }).populate('to', {
        avatar: 1,
        username: 1,
});
```
登录后查询friends时，只查了字段`from`等于当前用户ID的数据，没有查`to`等于当前用户ID的数据

#  解决方案：
查询 from = user._id or to = user._id 的数据即可

**Comment by yinxin630** [comment]
fiora 的好友功能是单向关系, 所以现在的逻辑没有问题.
被加好友的一方, 对他来说是收到一个陌生人私聊消息, 重新登录后确实是丢失, 这种情况正在考虑优化
