### ISSUE TITLE
代码高亮是highlight.js?

### ISSUE THREAD

**Issue by plh97** [yinxin630/fiora#36]
还是推荐一下  prismjs   高亮吧。
未压缩仅增加20kb大小

而highlight.js我测的要增加700kb+
事实上我怎么找到他的呢，
嗯，我看他react 官网和mdn都用它高亮，所以入手试了一下

虽然经过webpack -p   nginx压缩，体积已经不是问题了，
但是首次加载页面渲染耗时还是值得优化

**Comment by yinxin630** [comment]
好, 抽空看看
