### ISSUE TITLE
VSCode Extension for Fiora

### ISSUE THREAD

**Issue by moonrailgun** [yinxin630/fiora#367]
Hi, I am working for a cooool project —— make a vscode extension for fiora. it will be a pure text client in vscode.

Here is my repo: [fiora-for-vscode](https://github.com/moonrailgun/fiora-for-vscode)

Create this issue for tell you or others what i am working, and its still in progress.

And if has any suggestion, please tell me. 

Thanks for your amazing project, fiora is a great chat room project.

**Comment by moonrailgun** [comment]
If possible, can you provide a icon for svg version? This helpful to show in sidebar(its named as activitybar in vscode)

**Comment by yinxin630** [comment]
Done. Thank you so much for doing this
