### ISSUE TITLE
在vps上部署有问题！

### ISSUE THREAD

**Issue by zrj866** [yinxin630/fiora#368]
输入yarn build:client && yarn move-dist后出现下面整个：
yarn run v1.22.10
error Command "build:client" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
求解

**Comment by zrj866** [comment]
![image](https://user-images.githubusercontent.com/74248712/115866768-b54bd080-a46c-11eb-8cbb-46c96cb6a1fe.png)
已经在path中了，奇了个怪

**Comment by yinxin630** [comment]
在 fiora 目录下执行命令
