### ISSUE TITLE
图片上传失败

### ISSUE THREAD

**Issue by Moebyte** [yinxin630/fiora#376]
[ERROR] default - [uploadFile] ENOENT: no such file or directory, open '/opt/fiora/public/Avatar/609ce7fea5bf0a76aceb88c9_1620897972719.png'

一定要配置CDN才能上传图片吗？

**Comment by yinxin630** [comment]
不需要的呀

**Comment by taiyi747** [comment]
大佬能不能给个解决办法QAQ，查来查去都查不到

**Comment by yinxin630** [comment]
@Moebyte @taiyi747 已修复, 更新下代码即可
