### ISSUE TITLE
客户端client.ts修改后无效果

### ISSUE THREAD

**Issue by taiyi747** [yinxin630/fiora#383]
![image](https://user-images.githubusercontent.com/63543716/119213341-f7f6dc00-baf0-11eb-96c1-757072acbb4e.png)
我在修改上传图片文件大小
![image](https://user-images.githubusercontent.com/63543716/119213357-1361e700-baf1-11eb-946f-19e864e71c2c.png)
多次修改也重新构建了，但是还是没有效果
控制台无输出错误信息QAQ

**Comment by taiyi747** [comment]
也尝试env文件，最终也是没效果

**Comment by yinxin630** [comment]
是不是页面有缓存, 清缓存试一下呢.
稍后我也会再测试下功能是否正常

**Comment by yinxin630** [comment]
在我的服务器上测试过, 没有问题的
