### ISSUE TITLE
发送文件类内容时（处于发送状态）点击撤销抛异常信息

### ISSUE THREAD

**Issue by xfy520** [yinxin630/fiora#392]
![图片](https://cdn.suisuijiang.com/ImageMessage/5e157e2cde251c0710aee412_1623228015113.png?x-oss-process=image/resize,w_325,h_200/quality,q_90&width=1404&height=862)

预期结果：友好提示，如图片未发送完成，不能撤销之类的

**Comment by yinxin630** [comment]
Fixed
