### ISSUE TITLE
Logotype for Fiora

### ISSUE THREAD

**Issue by zuurw** [yinxin630/fiora#41]
Hi @yinxin630 , my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by yinxin630** [comment]
Hi @zuurw , Thank you so much.
I need a logo for Fiora app. This is what I'm using right now. https://github.com/yinxin630/fiora-app/blob/master/icon.png
I hope the logo style to be consistent with Fiora.

**Comment by zuurw** [comment]
Hi @yinxin630, do you have any request for the logo? where can I get inspired to create the design?

Best Regards!

**Comment by yinxin630** [comment]
My main color: #4a90e2  rgb(74,144,226)
Themes: https://www.google.com/search?q=Squid+Girl&tbm=isch

**Comment by zuurw** [comment]
Hi @yinxin630, I create one design with lot of variations, for the concept of the logo I get inspired in the hair of the girl that looks like an arrow in the bottom and in a chat ballon.
I dont know if you like one of this logos, if not I can make other design.

Best Regards!
![work fiora](https://user-images.githubusercontent.com/40801473/43724883-0342ec7a-9993-11e8-872a-29595cb7981d.png)

**Comment by zuurw** [comment]
Hi @yinxin630, did you see my logo design for this project?

Best Regards!

**Comment by yinxin630** [comment]
Sorry, I forgot to reply.
At present, these kinds of things do not make me particularly like. Relatively speaking, I think the second one is better.

**Comment by zuurw** [comment]
Hi @yinxin630, do you have any idea for the logo?

**Comment by yinxin630** [comment]
😳Honestly, I don't understand design. There is no specific idea about the logo.
I want to be biased MAG（Manga, Anime and Games）
