### ISSUE TITLE
消息要刷新网页才能更新显示

### ISSUE THREAD

**Issue by killerqueen77771** [yinxin630/fiora#411]
每条新消息都要刷新一下网页才能加载出来。。不知道为什么，嘤嘤嘤

**Comment by killerqueen77771** [comment]
另外说一下，这个东东真的超棒！

**Comment by shenxiang216** [comment]
？？？ 赵亚鑫 ***@***.*** 签名由 网易邮箱大师 定制 在2021年07月17日 22:06，killerqueen77771 写道： 另外说一下，这个东东真的超棒！ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yinxin630** [comment]
Fixed. 请 pull master 分支最新代码
