### ISSUE TITLE
为什么非要在七牛上存储文件？

### ISSUE THREAD

**Issue by freshbird** [yinxin630/fiora#42]
无意间发现这个工具，我们不想在常规聊天（比如QQ\微信）上沟通，这个工具能够自建聊天环境进行沟通，正好符合我们的需要，但仔细看看却发现有点问题，肯定有很多人像我们一样，需要的是一个自建的私聊工具，聊天规模并不大，但隐私要求较高，那么为什么不把相关的聊天文件存储在服务器本地呢？七牛是需要实名认证的，既然我们不想在QQ这些工具上聊天，同样也不想把个人真实信息留存在七牛，如果把这个工具弄成没有七牛就不能使用，就失去了它应有的意义不是吗。建议作者考虑一下此需求，一个方便搭建，又方便使用，且聊天过程自主控制，人员隐私得到保护的工具，一定会非常受欢迎的。

**Comment by yinxin630** [comment]
服务器流量贵并且带宽有限, 比如发了一张1MB的图片, 10个人在线, 总流量就是10MB. 用着玩玩还行, 实际肯定得存CDN. 之前版本是支持存服务器的, 新版没写这个逻辑, 很好实现的

**Comment by freshbird** [comment]
建议增加本地存储方式，现在买VPS动辄20M带宽无限流量，不必过于担心服务器的流量问题，图片也可以做上传后压缩+原图下载的方式，常规聊天就显示压缩图片，需要放大看细节了就可以下载原图查看。

**Comment by yinxin630** [comment]
嗯, 近期会支持一下

**Comment by yinxin630** [comment]
已支持, 文件将会上传到服务端 `public` 目录下
