### ISSUE TITLE
命令行工具语言环境默认值

### ISSUE THREAD

**Issue by smyhw** [yinxin630/fiora#429]
https://github.com/yinxin630/fiora/blob/4e0890f6ac2df96496ee933e3d977b95ae7496f9/packages/i18n/node.index.ts#L6-L16  
咱觉着，这里应该有一个默认值之类的东西，  
不然，当终端语言环境非预期时，执行命令行就直接抛错了  
![image](https://user-images.githubusercontent.com/47166461/129947207-f4a2122e-db06-4133-8949-f78a53b0a777.png)
比如，docker环境下，默认语言变量是空的：  
![image](https://user-images.githubusercontent.com/47166461/129947484-0712d1f1-2e3d-444c-af6e-2ad970eff82f.png)

**Comment by yinxin630** [comment]
很好的建议, 我来改一下
