### ISSUE TITLE
服务端异常崩溃

### ISSUE THREAD

**Issue by smyhw** [yinxin630/fiora#435]
![image](https://user-images.githubusercontent.com/47166461/130540732-889f8b80-b4ed-447b-90be-529ea9397ea2.png)

***

咱自己写客户端的时候发现的，咱也不了解nodejs，但是看着源码似乎是当客户端的发sendmessage包里没给callback参数时，就......

**Comment by yinxin630** [comment]
发一下调用接口的代码

**Comment by smyhw** [comment]
大概长这样就会触发

![image](https://user-images.githubusercontent.com/47166461/130543771-22c92f9c-af6f-4ac0-be46-a9e7b529339d.png)

如果服务端有异常消息，比如room id不存在之类的，直接就抛error退出了

**Comment by yinxin630** [comment]
第三个参数应该是一个 callback 函数, 用于接收 response data. Python 里不清楚是否一样, 你试试吧

**Comment by smyhw** [comment]
`__sio__.emit('sendMessage', {'to': room_id, 'type': 'text', 'content': msg}, callback=cb)`
这样写好像就可以了

但是但是，这个问题就是怕有人故意这么整，然后直接把服务端干掉。。。产生这个异常之后，服务端直接退出了

**Comment by yinxin630** [comment]
如果用 pm2 运行的话, 会自动重启进程. 
稍后我会测试下这种情况, 避免进程挂掉

**Comment by yinxin630** [comment]
我测试过了, 这个异常并不会杀死进程, 所以即便没有使用 pm2 值守也是没有问题的.
