### ISSUE TITLE
如何更好的管理用户

### ISSUE THREAD

**Issue by yinxin630** [yinxin630/fiora#447]
鉴于最近来了很多 00后, 10后, 搞得聊天室内乌烟瘴气, 需要提升管控手段

1. 在线一键删除用户
2. [done] 支持对离线用户进行 ip 封禁, 保存用户最近历史ip
3. [done] 发消息太频繁触发的小黑屋时间延长
4. [done] `deleteUser` 支持传入用户名
5. [done] 一键全员禁言
6. [done] 管理员删除消息不展示撤回提示

[done] 删除用户偶现 js error
```
Delete history result: { n: 16, ok: 1, deletedCount: 16 }
Delete messages created by this user
Delete result: { n: 439, ok: 1, deletedCount: 439 }
Leave the group that the user has joined
Leave fiora
Failed to delete user! Cannot read property 'toString' of null
```

**Comment by moonrailgun** [comment]
- 建议增加身份证识别，只允许成年用户加入
- 增加身份认证，改为邀请制
- 挪窝(比如tailchat这种具有极高私密性的聊天工具)。毕竟fiora默认公开群
