### ISSUE TITLE
failed to preview some pictures

### ISSUE THREAD

**Issue by lemos1235** [yinxin630/fiora#45]
显示的是内网的 ip 地址。

![image](https://user-images.githubusercontent.com/23135552/44942589-ac072480-ade7-11e8-9cf8-5bce5b441297.png)

**Comment by yinxin630** [comment]
是"发送图片"功能吗? 能给下具体的地址吗?

**Comment by lemos1235** [comment]
可能不只是图片发送功能，还有一个 avatar，显示的是内网 ip。

地址：https://lemo.site/

**Comment by yinxin630** [comment]
哦哦, 你应该是没有使用七牛cdn吧?
这个问题需要修改这里 https://github.com/yinxin630/fiora/blob/master/server/routes/system.js#L102

**Comment by yinxin630** [comment]
回头我修改一下

**Comment by yinxin630** [comment]
https://github.com/yinxin630/fiora/commit/3db80077a3b2a6ac48e1fbecbcc83e8b3bdf747f
拉下这次改动, 应该可以解决问题

**Comment by lemos1235** [comment]
你代码写错了，我tm..

**Comment by yinxin630** [comment]
现在还有错误吗?
前面这个问题主要是我没测过线上不用七牛的情况, 不好测..

**Comment by lemos1235** [comment]
```
url: `${process.env.NODE_ENV === 'production' ? ''
```
这个错误改一下。我用的 docker，线上不好改。

**Comment by yinxin630** [comment]
@lemos1235 这块是有什么错误...

**Comment by lemos1235** [comment]
之前看错了，抱歉。发现是这个系统环境变量没有设置，我设置了一下就环境变量好了。

![image](https://user-images.githubusercontent.com/23135552/44983691-a3ac1680-afac-11e8-8617-9cf2d2b5f7bf.png)

**Comment by yinxin630** [comment]
哦哦, 没问题了是吧?

**Comment by lemos1235** [comment]
问题不大，就是默认应该设置的环境变量其实没有设置进去。我猜可能是build文件哪个地方有问题，不过也有可能是别的问题。

**Comment by lemos1235** [comment]
还有一个地方呢，

![image](https://user-images.githubusercontent.com/23135552/45095239-2faa7380-b150-11e8-92fb-a74dfbe98db9.png)
@yinxin630 

还有就是把环境变量检测一下，看看到底有没有设置那个变量。

**Comment by yinxin630** [comment]
这个变量我只能在文档里注明一下, 每个人域名都是不同, 或者干脆就是没域名, 不好检测

**Comment by lemos1235** [comment]
域名地址的问题，还是用相对路径(?)。一般开发模式是通过代理访问服务端吧？没有对static文件做处理吗？

**Comment by lemos1235** [comment]
我说的环境变量是，可能你没有在服务端设置NODE_ENV 的环境变量？我在命令行使用 env 命令没有找到那个变量。

**Comment by yinxin630** [comment]
NODE_ENV这个环境变量在服务端运行时是需要自己设置的, `export NODE_ENV=production`, 参考: https://github.com/yinxin630/fiora/blob/master/doc/INSTALL.ZH.md#%E7%AC%AC%E4%BA%94%E6%AD%A5-1  
我在本地开发时并不是通过代理访问服务端的, 就是ip+port直连的...

**Comment by lemos1235** [comment]
哦哦，对对对。 原来是在 package.json 里写的，这里是直接访问的。emm..还是尽量遵守 ror 的原则吧.
