### ISSUE TITLE
php能直接调用注册啥的接口么。

### ISSUE THREAD

**Issue by Ocyss** [yinxin630/fiora#451]
刚弄了个php的网站，想接入个在线聊天。那个php的网站写好了登陆系统，想直接用之前的账号，但之前用的mysql改起来太麻烦了。
就利用php的exec调用fiora register，然后权限不够，不能直接创建。

哎，不知道咋办了。

**Comment by yinxin630** [comment]
fiora 接口全部是基于 socket.io 的, 你需要使用 socket.io 的 php 实现来进行交互
