### ISSUE TITLE
那个默认语音播报在哪里改啊

### ISSUE THREAD

**Issue by Ocyss** [yinxin630/fiora#452]
刚注册的号，都不一定知道开了这个，突然一个消息。。。
这个能改默认关闭嘛？

**Comment by yinxin630** [comment]
[这里](https://github.com/yinxin630/fiora/blob/master/packages/web/src/localStorage.ts#L76)是初始值, 不支持通过 config 配置

你可以加个参数传 false 即可 `getSwitchValue(LocalStorageKey.SoundSwitch, false)`

或者也可以类比前一行从 config 获取值 `getSwitchValue(LocalStorageKey.SoundSwitch, config.soundSwitch)`, 然后修改 config 配置
