### ISSUE TITLE
About config/server.js  ——> env

### ISSUE THREAD

**Issue by lemos1235** [yinxin630/fiora#46]
相关配置信息从环境变量中读取，而不必修改 js 文件，实现配置分离。尤其使用 Docker 部署时，可以从 .env 文件中读取环境变量，方便部署。

**Comment by yinxin630** [comment]
大部分配置目前都是支持从命令行参数获取的, 我自己部署也是用的命令行参数
命令行参数定义: https://github.com/yinxin630/fiora/blob/master/utils/commandOptions.js

**Comment by yinxin630** [comment]
如果你需要更多值的话, 我可以添加

**Comment by lemos1235** [comment]
容器部署，其启动命令通常是固化来 build镜像里的，通常情况下，如果非要改的话可能需要重新 build镜像。而如果从 env 里读取，只需要修改下变量，再重新启动容器即可。
当然，从命令行参数读取的方式也很好，如果是手动从命令行启动的话。

**Comment by yinxin630** [comment]
已支持, 不过我没自测, 各参数名与命令行参数一致, 不过首字母要大写

**Comment by lemos1235** [comment]
按照规范，环境变量应该是全部大写或全部小写，用下划线分割 (比如  JAVA_HOME, NODE_ENV 这样子。
@yinxin630

**Comment by yinxin630** [comment]
@lemos1235 好的, 我抽空改一下
