### ISSUE TITLE
请教：ctx.socket.emit的第一个参数只能是字符串，为啥代码能用数组？

### ISSUE THREAD

**Issue by mofan20** [yinxin630/fiora#470]
const targetSockets = await Socket.find({ user: toUser?._id });
        const targetSocketIdList =
            targetSockets?.map((socket) => socket.id) || [];
        if (targetSocketIdList.length) {
            ctx.socket.emit(targetSocketIdList, 'message', messageData);
        }

请教这里为啥能用数组？
  ctx.socket.emit(targetSocketIdList, 'message', messageData);

**Comment by mofan20** [comment]
看懂了。。。tx

**Comment by yinxin630** [comment]
是支持的, 可以看下官方文档
