### ISSUE TITLE
文件上传是否可以支持本地存储

### ISSUE THREAD

**Issue by tianya12612** [yinxin630/fiora#492]
刚刚看了一下您的问题回答，似乎需要cdn才能上传大文件，但对于实际使用来说，有这个需求的人能够自行选择购买带宽更大的服务器，如果只能上传到cdn，那么上传大文件的cdn流量成本，比服务器自身的流量成本还贵。

**Comment by yinxin630** [comment]
不配置 CDN 就默认存储在本地, 但是只支持 <= 1MB 的小文件

**Comment by tianya12612** [comment]
> 不配置 CDN 就默认存储在本地, 但是只支持 <= 1MB 的小文件

请问有什么替代方案可以上传大文件吗？或者您是否可以付费定制这个功能，如果可以请联系我的邮箱adkyushu771@gmail.com
