### ISSUE TITLE
怎么关闭萌新期发言限制/小黑屋

### ISSUE THREAD

**Issue by biliyoyo520** [yinxin630/fiora#511]
气死我了气死我了
刚搭好聊天室，测试的时候发现萌新期发言限制5/min
限制就算了，管理员也会进小黑屋，并且进了直接失去管理员身份(暂时的)
请问怎么才能关掉/改掉这玩意

**Comment by yinxin630** [comment]
<https://github.com/yinxin630/fiora/blob/master/packages/server/src/app.ts#L94>
注释掉这行
