### ISSUE TITLE
发送中文字符，post请求返回502

### ISSUE THREAD

**Issue by joket1999** [yinxin630/fiora#55]
如题只有发送中文才这样：
![image](https://user-images.githubusercontent.com/6611880/56647267-c6ae4680-66b3-11e9-9634-eb2d412f8281.png)

**Comment by yinxin630** [comment]
请问有没有修改过 `config/server.js` 文件呢

**Comment by joket1999** [comment]
> 请问有没有修改过 `config/server.js` 文件呢

找到原因了，我nginx的配置问题

**Comment by yinxin630** [comment]
@tanzhihang 能麻烦说下具体原因吗, 方便后面的人参考, 多谢
