### ISSUE TITLE
移动版/管理员功能完善

### ISSUE THREAD

**Issue by sdjxxfz** [yinxin630/fiora#56]
1.手机chrome体验极差，能否开发移动版？
2.管理员功能缺失，封禁用户后无法解封
3.频道无法更名

不知道作者是否还在维护这个项目，咕咕咕的话也要说一声呀

**Comment by yinxin630** [comment]
1. 移动端我一直是以做app为目标的, 所以web版没考虑做移动端兼容. app使用者很少, 包括我自己也是很少用,  因此只完成了基本功能
2. 这个可以加
3. 这个也可以加

项目还是在维护的, 只是我越来越咸鱼...
争取下周更新一次

**Comment by sdjxxfz** [comment]
1.移动版只有APP是不行的呀，我觉得这个极其适合作为客服系统（会有可爱的机器人提示来消息哈哈哈），但是客户是不会有心情去下载APP的~
2.建议添加游客发言功能~
3.建议封禁不以用户为基准，以IP为基准。注册门槛太低，被封的用户不出2分钟就重新注册一个杀回来了。。

**Comment by sdjxxfz** [comment]
总之，这是一个很棒的系统，我很喜欢！谢谢作者们的辛苦开发！

**Comment by yinxin630** [comment]
APP/H5一直缺一个好的UI设计  
游客发言之前版本曾支持过, 会显得很混乱, 而且会连带的相关API逻辑变复杂, 现在注册成本很低, 暂时不准备支持游客. 后期或许会考虑以可自由开启/关闭的方式支持吧  
关于封ip这个, 之前一直有个问题, 就是服务端拿到的ip不是真实用户ip, 应该跟我反向代理有关系, 这个肯定会有的

**Comment by kongtir** [comment]
如果用浏览器的话,可以在浏览器中写一个数据,来标识该玩家.
然后按标识封禁,除非他卸载app或者清空浏览器缓存.
可以的话,希望能一起开发.

**Comment by yinxin630** [comment]
1. 移动端已经支持了, 并且支持pwa添加到主屏
2. 后续再支持, 目前一次封禁只有10分钟
3. 修改群组名已支持
