### ISSUE TITLE
Administrator ID and Password

### ISSUE THREAD

**Issue by sonofcrocus** [yinxin630/fiora#57]
Hello sir and thank you for this awesome app.

I wonder what is exactly the admin id and password or how can i access as admin to ban users.

Thank you.

**Comment by yinxin630** [comment]
You should find your userId(_id) in database. Then modify this: https://github.com/yinxin630/fiora/blob/master/config/server.js#L30

**Comment by sonofcrocus** [comment]
@yinxin630 Thank you alot sir it worked perfectly for me and again thank you for this awesome work.

**Comment by sonofcrocus** [comment]
One more question if you don't mind, do you have any idea how to dockerize the app ( creating one docker image for the database and one for client interface) ?

**Comment by yinxin630** [comment]
I used to make a docket image before. (https://hub.docker.com/r/suisuijiang/fiora) But it is based on the old version. I will consider updating the image later

**Comment by sonofcrocus** [comment]
Yes sir i'm running your awesome project locally and i'm having problems configuring Dockerfile.
I'd be grateful if you share the Dockerfile config for the client and server.
Thanks in advance. :D
