### ISSUE TITLE
娱乐功能, 支持猜拳和roll点

### ISSUE THREAD

**Issue by yinxin630** [yinxin630/fiora#60]
1. 服务端计算, 防作弊
2. 结果就先用文字展示
3. 用text消息类型还是新建一个? (方便以后拓展)
4. 征集文案

**Comment by imengmengda** [comment]
PH播放器功能，初始化打开默认隐藏，输入神秘代码之后开启

**Comment by yinxin630** [comment]
> PH播放器功能，初始化打开默认隐藏，输入神秘代码之后开启

其他需求新建个issue讨论哈..

**Comment by yinxin630** [comment]
![image](https://user-images.githubusercontent.com/6939365/60572455-3887c800-9da8-11e9-82bd-a3bac4f3a3e7.png)
dota中的roll点
