### ISSUE TITLE
掷点null bug

### ISSUE THREAD

**Issue by yinxin630** [yinxin630/fiora#68]
输入 `-roll [number]` 可复现

**Comment by iiuhuy** [comment]
- `-roll [3]`
- `-rps: 石头`
![image](https://user-images.githubusercontent.com/21032217/61424241-74449500-a945-11e9-894c-50cb95cc2902.png)

null    不支持的消息类型

**Comment by lidog** [comment]
你发错邮件了

在 2019-07-18 10:02:50，"碎碎酱" <notifications@github.com> 写道：


输入 -roll [number] 可复现
