### ISSUE TITLE
我是用docker安装的，发送图片时，上传图片的接口是给的fiora容器的私有ip

### ISSUE THREAD

**Issue by Declarcall** [yinxin630/fiora#82]
## 问题一：

**我是用docker安装的，发送图片时，上传图片的接口是给的fiora容器的私有ip**

我没配置七牛云，直接docker拉下来测试使用的（直接使用公网ip+端口的方式访问的）。试了下发送图片的功能，然后看到失败的请求是这样的 
```
Request:
Request URL: http://172.18.0.2:9200/ImageMessage_5d39ef70844b5a1889d6f05c_1164078411465.gif?width=120&height=120&imageView2/3/w/144/h/144
Request Method: GET
Status Code: 503 Service Unavailable

Response:
Connection: close
Date: Friday, 26-Jul-19 03:15:30 CST
Keep-Alive: timeout=58
```
其中 172.18.0.2 是我 fiora容器的私有ip。请问，这个问题该如何解决呢？

## 问题二

**发送表情包 - 搜索表情包 无法在页面显示表情图片**

由于微博已经根据Referrer来限制图片外链，如果没办法解决这个问题，建议放弃使用微博图床

**Comment by yinxin630** [comment]
问题一我再试试
问题二目前是爬的别的站的资源, 该站是用微博图床的, 我改不了. http协议应该是没限制外链的, 想根解只能下载图片到自己服务器上, 后面会考虑做一下

**Comment by yinxin630** [comment]
问题一参考 #113 
问题二请关注 #95
