### ISSUE TITLE
希望有一天提供多人语音功能

### ISSUE THREAD

**Issue by SoraKasvgano** [yinxin630/fiora#91]
类似discord网页语音功能干掉ts 233333

安装的时候提供编译安装，想部署在arm上。。。

**Comment by yinxin630** [comment]
个人不喜欢语言聊天, 后面会考虑做这个功能
至于怎么部署在arm上我就不怎么了解了, 现在是遇到什么问题了吗

**Comment by SoraKasvgano** [comment]
目前在斐讯N1上 armbian  docker安装FIORA 显示docker compose 版本不对好像。。。
我装的是最新的= =

**Comment by SoraKasvgano** [comment]
@yinxin630 armbian docker 显示如下：
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
root@aml:~/fiora#

**Comment by yinxin630** [comment]
你所安装的机器上, docker版本是多少呢?

**Comment by yinxin630** [comment]
看文档, 应该需要 docker 版本在 17.04.0+

**Comment by SoraKasvgano** [comment]
> 看文档, 应该需要 docker 版本在 17.04.0+

哎？我装的应该是这个系统分支最新的了= =，刚从阿里镜像下的。/
