### ISSUE TITLE
fiora添加桌面快捷方式闪退

### ISSUE THREAD

**Issue by threescs** [yinxin630/fiora#92]
![image](https://user-images.githubusercontent.com/29721759/62671324-ff56ff00-b9c8-11e9-9569-7d73695e8123.png)

**Comment by yinxin630** [comment]
@threescs 删掉pwa, 重启chrome, 重新安装pwa就好了. 不知道啥原因

**Comment by yinxin630** [comment]
![image](https://user-images.githubusercontent.com/6939365/62823795-c042cc80-bbc7-11e9-94fa-639799ee9f41.png)
删除前应用文件名是 `Default xxx.app`, 重新安装变成了 `fiora.app`, 不知道是不是 Chrome 版本更新的缘故
