### ISSUE TITLE
语音播报功能支持其他客户端以及选择性播报

### ISSUE THREAD

**Issue by Neukchill** [yinxin630/fiora#93]
希望语音播报功能可以添加对移动端的支持，可选群组或好友不播报

**Comment by yinxin630** [comment]
mac是啥情况不支持?

**Comment by Neukchill** [comment]
> MAC是啥情况不支持？

支持，抱歉，之前测试没播报来着，刚刚试了下可以了

**Comment by yinxin630** [comment]
选择性播报是指什么? 是需要播报自己的消息吗

**Comment by yinxin630** [comment]
APP暂时没有更新打算, 准备web版兼容移动端

**Comment by Neukchill** [comment]
> APP暂时没有更新打算，准备web版兼容移动端

也可以，兼容移动端了也行，app搞不明白，不过日后希望会有app！因为方便~

**Comment by Neukchill** [comment]
> 选择性播报是指什么? 是需要播报自己的消息吗

播报自己消息希望也会有，因为有很多人向我也提出过，我来反馈+1，可以在自己的设置里面设置播报自己的文字。

**Comment by yinxin630** [comment]
ok, 这个我争取近期加上
APP目前主要是部分功能开发起来困难, 比如文字和表情混排, 代码消息. 另外ios app需要买开发者证书才能上架应用, 也是一笔开销

**Comment by Neukchill** [comment]
> 好的，这个我争取近期加上
> APP目前主要是部分功能开发起来困难，比如文字和表情混排，代码消息。另外ios app需要买开发者证书才能上架应用，也是一笔开销

<strike>免费证书XD</strike>

**Comment by yinxin630** [comment]
播报自己消息的功能开关已经加上了, 在设置中开启, 默认关闭

**Comment by Neukchill** [comment]
> 播报自己消息的功能开关已经加上了, 在设置中开启, 默认关闭

好的 辛苦了
